[mgr]
ratio = [ 1, 3, 4 ]
sort_by = "mtime"
sort_sensitive = false
sort_reverse = true
sort_dir_first = true
linemode = "mtime"

[[plugin.prepend_previewers]]
url = "*/"
run = "eza-preview"

[[plugin.prepend_previewers]]
mime = "image/*"
run = 'faster-piper -- "$HOME/.config/yazi/scripts/media-preview.sh" "$1" "$w" "$h"'

[[plugin.prepend_previewers]]
mime = "{audio,video}/*"
run = 'faster-piper -- "$HOME/.config/yazi/scripts/media-preview.sh" "$1" "$w" "$h"'

[[plugin.prepend_previewers]]
mime = "text/markdown"
run = 'faster-piper -- glow -w $w "$1"'

[[plugin.prepend_previewers]]
mime = "application/pdf"
run = 'faster-piper -- pdftoppm -r 220 -f 1 -singlefile -png "$1" | viu -w $w -'

[[plugin.prepend_previewers]]
mime = "application/bittorrent"
run = "torrent-preview"

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd}"
run = "ouch"

[opener]
image = [
	{ run = 'lightningview %s1; hyprctl dispatch focuswindow "title:^(yazi)$"', block = true, desc = "LightningView", for = "unix" },
]

edit = [
	{ run = 'hx %s', block = true, desc = "Helix", for = "unix" },
]

extract = [
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[open]
prepend_rules = [
	{ mime = "image/*", use = "image" },
	{ mime = "text/*", use = "edit" },
	{ mime = "application/json", use = "edit" },
]

[[plugin.prepend_fetchers]]
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"
group = "mime"

[[plugin.prepend_fetchers]]
url   = "remote://*"
run   = "mime-ext.remote"
prio  = "high"
group = "mime"

[preview]
image_delay = 0
