[mgr]
ratio = [ 1, 3, 4 ]
sort_by = "mtime"
sort_sensitive = false
sort_reverse = true
sort_dir_first = true
linemode = "mtime"

[[plugin.prepend_previewers]]
mime = "image/*"
run = 'faster-piper -- viu -w $w "$1"'

[[plugin.prepend_previewers]]
mime = "application/pdf"
run = 'faster-piper -- pdftoppm -r 220 -f 1 -singlefile -png "$1" | viu -w $w -'

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd}"
run = "ouch"

[opener]
extract = [
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[[plugin.prepend_fetchers]]
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"
group = "mime"

[[plugin.prepend_fetchers]]
url   = "remote://*"
run   = "mime-ext.remote"
prio  = "high"
group = "mime"

[preview]
image_delay = 0
