theme = "kanagawa"

[editor]
line-number = "absolute"
mouse = false
color-modes = true
bufferline = "multiple"
cursorline = true
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"

[keys.normal.space]
w = ":write"
W = ":write-all"
q = ":quit"
Q = ":write-quit-all"
x = ":quit!"
X = ":quit-all!"

[keys.select]
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
R = "replace_selections_with_clipboard"
