$terminal = kitty
$panel = wayle panel start
$filemanager_gui = nautilus
$filemanager_term = kitty yazi
$menu = fuzzel
$browser = firefox
$mail = thunderbird
$code_editor = zed-editor
$text_editor = gnome-text-editor
$cursor_theme = Bibata-Original-Ice
$cursor_size = 25
