exec-once = $terminal
exec-once = $panel
exec-once = hyprscratch init
exec-once = hyprctl plugin load "/usr/lib64/hyprland/dynamic-cursors.so"
exec-once = ~/.config/hypr/scripts/start_hyprlax.sh
exec-once = telegram-desktop
exec-once = fractal
exec-once = firefox
exec-once = thunderbird
exec-once = /usr/libexec/polkit-1/polkit-gnome-authentication-agent-1
exec-once = hyprland-per-window-layout
exec-once = nm-applet
exec-once = blueman-applet
exec-once = logitune
exec-once = cclipd -s 25 -t "image/png" -t "image/*" -t "text/plain;charset=utf-8" -t "text/*" -t "*"
