daemon_options = clean

terminal {
    title = float_terminal
    command = kitty --title float_terminal
    options = persist
}

monitoring {
    title = monitoring
    command = kitty --title monitoring btm
    options = persist
}

subtui {
    title = subtui
    command = kitty --title subtui subtui
    options = persist
}

yazi {
    title = yazi
    command = kitty --title yazi yazi
    options = persist
}
