[bar]
scale = 0.800000011920929
bg = "bg-surface-elevated"
button-variant = "basic"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "media",
    "window-title",
]
center = ["hyprland-workspaces"]
right = [
    "custom-updates",
    "volume",
    "notifications",
    "keyboard-input",
    "systray",
    "clock",
    "weather",
    "dashboard",
]

[styling.palette]
bg = "#1a1a22"
surface = "#1f1f28"
elevated = "#2a2a37"
fg = "#dcd7ba"
fg-muted = "#727169"
primary = "#957fb8"
red = "#e82424"
yellow = "#dca561"
green = "#98bb6c"
blue = "#7e9cd8"

[modules.clock]
format = "%T %d.%m.%Y"
icon-color = "#dcd7ba"
label-color = "#dcd7ba"
dropdown-show-seconds = true

[modules.dashboard]
icon-override = "si-linux-symbolic"
icon-color = "#dcd7ba"
right-click = "/usr/bin/wayle-settings"
dropdown-lock-command = "hyprlock"

[modules.hyprland-workspaces]
show-special = false
app-icons-show = true
active-indicator = "underline"
active-color = "#dcd7ba"

[modules.keyboard-input]
icon-color = "#dcd7ba"
label-color = "#dcd7ba"

[modules.keyboard-input.layout-alias-map]
"English (US)" = "US"
Russian = "RU"

[modules.media]
format = "{{ artist }} - {{ title }}"
icon-color = "#dcd7ba"
label-color = "#dcd7ba"
label-max-length = 50

[modules.notifications]
icon-color = "#dcd7ba"
label-color = "#dcd7ba"
popup-position = "bottom-center"
popup-max-visible = 3

[modules.volume]
icon-color = "#dcd7ba"
label-color = "#dcd7ba"
right-click = "wayle audio output-mute"
middle-click = ""
scroll-up = "wayle audio output-volume +1"
scroll-down = "wayle audio output-volume -1"

[modules.weather]
location = "Obninsk"
icon-color = "#dcd7ba"
label-color = "#dcd7ba"

[modules.window-title]
icon-color = "#dcd7ba"
label-color = "#dcd7ba"

[[modules.custom]]
id = "updates"
command = "~/.config/wayle/scripts/check_updates.sh"
mode = "poll"
interval-ms = 21600000
restart-policy = "never"
restart-interval-ms = 1000
format = "{{ text }}"
tooltip-format = "{{ tooltip }}"
hide-if-empty = false
icon-name = "ld-refresh-cw-symbolic"
class-format = "{{ class }}"
icon-show = true
icon-color = "#dcd7ba"
icon-bg-color = "auto"
label-show = true
label-color = "#dcd7ba"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "auto"
left-click = "kitty --title float_terminal ~/.config/wayle/scripts/update_system.sh"
right-click = ""
middle-click = ""
scroll-up = ""
scroll-down = ""

[osd]
border = false

[wallpaper]
engine-enabled = false
