exec-once = $terminal
exec-once = $panel
exec-once = hyprctl plugin load "/usr/lib64/hyprland/hyprexpo.so"
exec-once = hyprctl plugin load "/usr/lib64/hyprland/dynamic-cursors.so"
exec-once = hyprctl setcursor $cursor_theme $cursor_size
exec-once = hyprpaper
exec-once = ayugram-desktop
exec-once = fractal
exec-once = firefox
exec-once = thunderbird
exec-once = /usr/libexec/polkit-1/polkit-gnome-authentication-agent-1
exec-once = swaync
exec-once = hyprland-per-window-layout
exec-once = nm-applet
exec-once = blueman-applet
exec-once = logitune
exec-once = cclipd -s 25 -t "image/png" -t "image/*" -t "text/plain;charset=utf-8" -t "text/*" -t "*"
