windowrule = match:class ^(firefox)$, workspace 2 silent
windowrule = match:class ^(thunderbird)$, workspace 3 silent
windowrule = match:class ^(org.telegram.desktop)$, workspace 4 silent
windowrule = match:class ^(org.gnome.Fractal)$, workspace 4 silent

windowrule = match:class ^(com.saivert.pwvucontrol)$, float on
windowrule = match:class ^(com.saivert.pwvucontrol)$, move onscreen cursor 5% 5%

windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(blueman-manager)$, move onscreen cursor 5% 5%

windowrule = match:title ^(float_terminal)$, float on
windowrule = match:title ^(float_terminal)$, size 1500 900

windowrule = match:title ^(monitoring)$, float on
windowrule = match:title ^(monitoring)$, size 1500 900

windowrule = match:class ^(org.gnome.Nautilus)$, float on
windowrule = match:class ^(org.gnome.Nautilus)$, size 1500 900

windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(xdg-desktop-portal-gtk)$, size 1500 900

windowrule = match:class ^(com.interversehq.qView)$, match:title negative:^(Информация о файле)$, maximize on
windowrule = match:class ^(com.interversehq.qView)$, match:title ^(Информация о файле)$, float on
windowrule = match:class ^(com.interversehq.qView)$, match:title ^(Информация о файле)$, size 400 300

windowrule = match:class ^(org.gnome.Loupe)$, maximize on
windowrule = match:class ^(org.gnome.Showtime)$, maximize on
windowrule = match:class ^(swayimg)$, maximize on

windowrule = match:class ^(io.bassi.Amberol)$, float on
windowrule = match:class ^(io.bassi.Amberol)$, move onscreen 80% 5%
